[package]
name = "rustlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.63"
log = "0.4.18"
wasm-bindgen = "0.2.86"

[lib]
crate-type = ["cdylib"]
